name: Release Image

on:
  push:
    tags:
      - 'v*.*.*' # Trigger on version tags

  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ secrets.DOCKER_MACHINE_USER }}
        password: ${{ secrets.DOCKER_MACHINE_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v6
      if: !startsWith(github.ref_name, 'v')
      with:
        push: true
        platforms: linux/amd64,linux/arm64
        tags: ghcr.io/port-labs/port-sender:${{ github.ref_name }}

    - name: Build and push with latest tag
      uses: docker/build-push-action@v6
      if: startsWith(github.ref_name, 'v')
      with:
        push: true
        platforms: linux/amd64,linux/arm64
        tags: ghcr.io/port-labs/port-sender:${{ github.ref_name }},ghcr.io/port-labs/port-sender:latest
